"""
Risk Schema for Agent 4 (Risk Management Agent)

Purpose:
Defines the structured risk management decision
generated after signal evaluation.

This schema standardizes:
- trade approval
- veto logic
- risk governance
"""

from pydantic import BaseModel
from schemas.signal_schema import SignalOutput


class RiskOutput(BaseModel):

    # Original signal generated by Agent 3
    signal: SignalOutput

    # Whether the trade is approved
    approved: bool

    # Explanation if trade is rejected
    veto_reason: str